
// Modified by claude to give desired structured output
const { GoogleGenAI } = require("@google/genai");
const { buildPrompt } = require("./Promptbuilder");
const  {z}  =require("zod")
const {zodToJsonSchema} = require("zod-to-json-schema")
const puppeteer = require('puppeteer')

const ai = new GoogleGenAI({
  apiKey: process.env.GEMINI_API_KEY,
});

const responseSchema = {
  type: "object",
  required: ["matchScore", "title", "technicalQuestionsSchema", "behaviouralQuestionsSchema", "skillGapSchema", "preparationPlanSchema"], // 👈 match exact property names
  properties: {
    matchScore: { type: "number" },
    title: { type: "string" },
    technicalQuestionsSchema: {
      type: "array",
      items: {
        type: "object",
        required: ["question", "intention", "answer"],
        properties: {
          question: { type: "string" },
          intention: { type: "string" },
          answer: { type: "string" },
        },
      },
    },
    behaviouralQuestionsSchema: {
      type: "array",
      items: {
        type: "object",
        required: ["question", "intention", "answer"],
        properties: {
          question: { type: "string" },
          intention: { type: "string" },
          answer: { type: "string" },
        },
      },
    },
    skillGapSchema: {
      type: "array",
      items: {
        type: "object",
        required: ["skill", "severity"],
        properties: {
          skill: { type: "string" },
          severity: { type: "string", enum: ["low", "medium", "high"] },
        },
      },
    },
    preparationPlanSchema: {
      type: "array",
      items: {
        type: "object",
        required: ["day", "focus", "tasks"],
        properties: {
          day: { type: "number" },
          focus: { type: "string" },
          tasks: { type: "array", items: { type: "string" } },
        },
      },
    },
  },
};

async function generateInterviewReport({ resume, selfDescription, jobDescription }) {
  const prompt = buildPrompt(resume, selfDescription, jobDescription);

  const response = await ai.models.generateContent({
    model: "gemini-3.5-flash",
    contents: prompt,
    config: {
      responseMimeType: "application/json",
      responseSchema: responseSchema,
    },
  });

  const result = JSON.parse(response.text);
  // console.log(JSON.stringify(result, null, 2));
  return result
}


async function generatePdfFromHtml(htmlContent){

  const browser = await puppeteer.launch()
  const page = await browser.newPage()
  await page.setContent(htmlContent,{waitUntil:"networkidle0"})

  const pdfBuffer = await page.pdf({format:"A4",margin:{
    top:"20mm",
    bottom:"20mm",
    left:"15mm",
    right:"15mm"
  }})

  await browser.close()

  return pdfBuffer


}


async function generatePdfResume({resume,selfDescription,jobDescription}){

  const resumePdfSchema = z.object({
    html: z.string().describe("The HTML content of the resume which can be converted to PDF using any library like puppeteer")
  })
  
   const prompt = `Generate resume for a candidate with the following details:
                        Resume: ${resume}
                        Self Description: ${selfDescription}
                        Job Description: ${jobDescription}

                        the response should be a JSON object with a single field "html" which contains the HTML content of the resume which can be converted to PDF using any library like puppeteer.
                        The resume should be tailored for the given job description and should highlight the candidate's strengths and relevant experience. The HTML content should be well-formatted and structured, making it easy to read and visually appealing.
                        The content of resume should be not sound like it's generated by AI and should be as close as possible to a real human-written resume.
                        you can highlight the content using some colors or different font styles but the overall design should be simple and professional.
                        The content should be ATS friendly, i.e. it should be easily parsable by ATS systems without losing important information.
                        The resume should not be so lengthy, it should ideally be 1-2 pages long when converted to PDF. Focus on quality rather than quantity and make sure to include all the relevant information that can increase the candidate's chances of getting an interview call for the given job description.
                    `

   const response = await ai.models.generateContent({
    model:"gemini-2.5-flash",
    contents:prompt,
    config:{
      responseMimeType:"application/json",
      responseSchema:zodToJsonSchema(resumePdfSchema)
    }

   })

   const jsonContent = JSON.parse(response.text)
   const pdfBuffer = await generatePdfFromHtml(jsonContent.html)
   return pdfBuffer

}

module.exports = {generateInterviewReport,generatePdfResume};









